"""New relation with gender and teacher there

Revision ID: 5e21128963f7
Revises: 
Create Date: 2024-06-25 10:09:40.510348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e21128963f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_event', sa.Column('vanue', sa.String(), nullable=False, server_default='default_value'))
    op.drop_column('annual_event', 'location')
    op.add_column('event', sa.Column('vanue', sa.String(), nullable=False))
    op.drop_column('event', 'location')
    op.add_column('teacher', sa.Column('gender_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teacher', 'gender', ['gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'gender_id')
    op.add_column('event', sa.Column('location', sa.VARCHAR(), nullable=False, server_default='default_value'))
    op.drop_column('event', 'vanue')
    op.add_column('annual_event', sa.Column('location', sa.VARCHAR(), nullable=False, server_default='default_value'))
    op.drop_column('annual_event', 'vanue')
    # ### end Alembic commands ###
