"""added column media_filename

Revision ID: 902e0e02484d
Revises: 5c6630d0aadc
Create Date: 2024-05-27 21:14:19.171199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902e0e02484d'
down_revision = '5c6630d0aadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('media_filename', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'media_filename')
    # ### end Alembic commands ###
